### ISSUE TITLE
Implement Linting for TypeScript and python

### ISSUE THREAD

**Issue by pontuss95** [antonericson/yars#8]
@Jaagarn  has discovered that the indentation is not consistent throughout the codebase. He used slangs as "Filthy tabs" and so on, he was very distraught by this finding so he couldn't muster the motivation needed to write up this Issue. Therefore, i'm writing it on his behalf.

Very urgent. Fix pls soon

**Comment by pontuss95** [comment]
![image](https://user-images.githubusercontent.com/49024892/231253605-51715c2d-5de2-4725-bf79-cf87ec88d4ba.png)

**Comment by antonericson** [comment]
Important, document in readme or contributing file what linting settings we use project-wide

**Comment by pontuss95** [comment]
This can be considered solved with kroksos linting jobs?
